services:

  backend:
    build: server
    ports:
      - "5000:5000"
    networks:
      - ecommerce
    volumes:
      - ./server/.env:/app/.env

  frontend:
    build: client
    ports:
      - "3000:3000"
    networks:
      - ecommerce
    volumes:
      - ./client/.env:/app/.env

networks:
  ecommerce:
    driver: bridge